wandb:
  project_name: predicting_bank_customer_churn
pipeline_steps:
  - split_data
data_path: /home/khaled/projects/predicting_bank_customer_churn/data/bank_customer_churn_prediction.csv
test_size: 0.33